Create notes app. Adding notes, deleting notes and updating notes work.
tamokakhidze/NotesApplication pull request #1
Opened 2024-11-04 13:04 UTC by tamokakhidze

2024-11-04 13:11 UTC, GujMeister requested changes
Understandable code with minor stylistic mistakes which should be fixed before resubmitting

2024-11-04 13:11 UTC, GujMeister commented on NotesApp/CoreData/CoreDataManager.swift
>  import Foundation
Remove "import Foundation"

2024-11-04 13:11 UTC, GujMeister commented on NotesApp/CoreData/CoreDataManager.swift
> +    private init() {}
Separate initialisation method from other properties

2024-11-04 13:11 UTC, GujMeister commented on NotesApp/Customs/BlackAlertController.swift
>  class BlackAlertController: UIView {
Try to make classes that will not be subclassed "final"

2024-11-04 13:11 UTC, GujMeister commented on NotesApp/Scenes/MainVC/ViewController.swift
> +
Remove whitespace on 152nd line

2024-11-04 13:11 UTC, GujMeister commented on NotesApp/Scenes/MainVC/ViewModel.swift
> +
Remove whitespace on 13th line

2024-11-04 13:28 UTC, GujMeister approved these changes
Thanks for resolving the problems stated above.

2024-11-04 14:51 UTC, AnaIoramashvili requested changes
In NoteCell please change the font size. The fond size should be: 16

2024-11-04 14:55 UTC, AnaIoramashvili approved these changes
Great Job!

2024-11-04 14:55 UTC, merged

2024-11-06 06:37 UTC, AniDzamelashvili commented on NotesApp/Customs/BlackAlertController.swift
> +    private lazy var icon: UIImageView = {
Do you really need to have lazy properties for icon and alertmessahe?

2024-11-06 06:38 UTC, AniDzamelashvili commented on NotesApp/Customs/BlackAlertController.swift
> +
Please have seperate functions as I mentioned above

2024-11-06 06:40 UTC, AniDzamelashvili commented on NotesApp/Customs/NoteCell.swift
Same comment here, not write everything in init.

2024-11-06 06:42 UTC, AniDzamelashvili commented on NotesApp/Customs/NoteCell.swift
> +        let deleteButton = UIButton()
why are you preferring having properties like this? you were writing inBlackALertView properties with closure. currently inside this you are having everything like adding subviews, constraints ...

2024-11-06 06:43 UTC, AniDzamelashvili commented on NotesApp/Scenes/AddNoteVC/AddNoteViewController.swift
> +    private func configureTitleTextField() {
You were writing inBlackALertView properties with closure. currently inside this you are having everything like adding subviews, constraints ... take a look to inBlackALertView file

2024-11-06 06:44 UTC, AniDzamelashvili commented on NotesApp/Scenes/AddNoteVC/AddNoteViewController.swift
> +
fix indentation

2024-11-06 06:45 UTC, AniDzamelashvili commented on NotesApp/Scenes/MainVC/ViewController.swift
> +        1
avoid using hardcoded numbers